version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:8000"

    environment:
      REDIS_URL: redis://redis:6379
      NODE_OPTIONS: --max-old-space-size=8192 # Feel free to adjust
    mem_limit: 8g # Feel free to adjust

volumes:
  redis-data:
