version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - minio
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: chilingaryans-media-service
    # command: ["node", "dist/main.js"]
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  redis-data:
  minio-data:
